version: "3.3"

services:
  db:
    image: postgres:14.1
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: user_role_management_db
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


  django_gunicorn:
    volumes:
      - .:/app
      - static:/static
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/production.Dockerfile
    container_name: django_gunicorn
    command: >
      bash -c "sleep 3 &&
                python manage.py makemigrations &&
                python manage.py migrate &&
                sleep 5 &&
                python manage.py collectstatic --clear --noinput &&
                python manage.py collectstatic --noinput &&
                gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8061:8000"
    depends_on:
      - db
    restart: on-failure

volumes:
  static:
